# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
