# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='god',
            field=models.BooleanField(default=1),
        ),
    ]
