# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0002_auto_20170424_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
