# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0003_auto_20170424_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
    ]
