# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0004_auto_20170510_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='descripcion',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
